require("visual-multi").setup({
  wrap = true,
  case_sensitive = true,
  mappings = {
    find_next = "<C-n>",
    select_all = "<C-d>",
    select_left = "<C-Left>",
    select_right = "<C-Right>",
    add_cursor_up = "<C-Up>",
    add_cursor_down = "<C-Down>",
    add_cursor = "<C-x>",
    add_cursor_word = "<C-w>",
    skip_region = false,
    remove_region = "q",
    insert_paste = "<C-v>",
    undo = "u",
    redo = "<C-r>",
  },
  highlights = {
    cursor = { bg = "#87afff", fg = "#4e4e4e" },
    cursor_active = { bg = "#dfdf87", fg = "#4e4e4e" },
    insert = { bg = "#4c4e50" },
    insert_active = { bg = "#4c4e50" },
    selection = { bg = "#005faf" },
    selection_active = { bg = "#87afff", fg = "#4e4e4e" },
  },
})
