general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[font]
builtin_box_drawing = true
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"

# [font]
# normal = { family = "JetBrainsMono Nerd Font" }
# bold = { family = "JetBrainsMono Nerd Font" }
# italic = { family = "JetBrainsMono Nerd Font" }
# size = 14

[window]
padding.x = 14
padding.y = 14
# decorations = "None"

[window.dimensions]
columns = 126
lines = 35

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" },
{ key = "Return", mods = "Shift", chars = "\u001B\r" }
]
